<?php

use App\Support\Resources;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Str;

/*
| php artisan docs:schema > ../docs/04-DATABASE-SCHEMA.md
| Writes the schema document from config/resources.php, so the docs cannot drift from the migration.
*/
Artisan::command('docs:schema', function () {
    $types = ['s' => 'VARCHAR(191) NULL', 't' => 'TEXT NULL', 'i' => 'INT DEFAULT 0', 'm' => 'BIGINT DEFAULT 0 (rupiah)', 'd' => 'DECIMAL(8,2) DEFAULT 0', 'b' => 'TINYINT(1) DEFAULT 0', 'j' => 'JSON NULL'];
    $out = [
        '# 04 — Database Schema', '',
        'MySQL 8 / MariaDB 10.6+, InnoDB, `utf8mb4_unicode_ci`. Created only by migrations (`backend/database/migrations`).',
        'Generated by `php artisan docs:schema` from `backend/config/resources.php` — do not edit by hand.', '',
        '## Relationships', '', '```',
        'users 1─1 students (students.user_id, unique)',
        'users 1─n <tutor tables>.owner_id (nullOnDelete)',
        'students 1─n course_enrollments n─1 courses        unique(student_id, course_id)',
        'courses 1─n course_modules 1─n lessons             cascade delete',
        'students 1─n lesson_progress n─1 lessons           unique(student_id, lesson_id)',
        'assignments 1─n submissions                        unique(assignment_id, student_id)',
        'students 1─n bills / student_subjects / student_attendances / certificates (student_ref)',
        '```', '',
        '## Core tables', '',
        '| Table | Purpose | Columns | Keys |', '|---|---|---|---|',
        '| `users` | Accounts for all roles | id, name, email, password (bcrypt), role (admin/guru/siswa), phone, status, avatar, profile JSON, timestamps | unique(email), index(role) |',
        '| `personal_access_tokens` | Sanctum API tokens | tokenable, name, token (sha256), abilities, last_used_at, expires_at | unique(token) |',
        '| `password_reset_tokens` | Reset links | email, token, created_at | pk(email) |',
        '| `course_modules` | Chapters of a course | id, ref, course_id, title, locked, position | unique(ref), fk course_id → courses (cascade) |',
        '| `lessons` | Lessons of a module | id, ref, module_id, title, kind, duration, video_url, about, notes JSON, files JSON, position | unique(ref), fk module_id → course_modules (cascade) |',
        '| `course_enrollments` | Student ↔ course | id, student_id, course_id | unique(student_id, course_id), fks cascade |',
        '| `lesson_progress` | Completed lessons | id, student_id, lesson_id, completed_at | unique(student_id, lesson_id), fks cascade |',
        '| `settings` | Institution settings | key, value | pk(key) |',
        '', '## Resource tables', '',
        'Every table below also has `id` BIGINT PK, `ref` VARCHAR(40) UNIQUE (the public id returned as `id` by the API) and timestamps.',
        'Tutor-owned tables add `owner_id` (FK → users); student-owned tables are indexed on their owner column.', '',
    ];
    foreach (Resources::names() as $name) {
        $def = Resources::def($name);
        $out[] = '### `'.Resources::table($name).'` — `/api/r/'.$name.'`';
        $out[] = '';
        $out[] = 'Read: '.implode(', ', $def['read']).' · Write: '.implode(', ', $def['write'])
            .(isset($def['owner']) ? ' · Owner scope: '.$def['owner'].' (`'.Resources::ownerColumn($name).'`)' : '')
            .' · Required: '.implode(', ', $def['req']);
        $out[] = '';
        $out[] = '| Column | Type | JSON key |';
        $out[] = '|---|---|---|';
        foreach (Resources::columns($name) as $col => $spec) {
            $type = $spec['nullable'] || $col === 'user_id' ? preg_replace('/ DEFAULT 0.*/', ' NULL', $types[$spec['type']]) : $types[$spec['type']];
            $out[] = "| `$col` | $type | `".Str::camel($col).'` |';
        }
        $out[] = '';
    }
    $this->line(implode("\n", $out));
})->purpose('Print docs/04-DATABASE-SCHEMA.md from the resource registry');
